language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t jrunning/docker-react -f Dockerfile . 

# script:
#   - docker run -e CI=true jrunning/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-531836388365"
  bucket_path: "docker-react"
  on:
    branch: feature
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY