language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t jrunning/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jrunning/docker-react npm run test